export const HOME = "/"
export const SIGNUP = "/signup"
export const SIGNIN = "/signin"
export const SIGNOUT = "/signout"
export const DASHBOARD = "/dashboard"
export const ADASHBOARD = "/adminDashboard"
export const CART = "/cart"
